### ISSUE TITLE
How to make GitHub packages public?

### ISSUE THREAD

**Issue by VeiZhang** [chenzhang2006/AndroidLibForArtifactory#3]
It seems a private package, if I want to use your package, how to do?

**Comment by chenzhang2006** [comment]
This repo should have been public for a while. I just double checked. Feel free to download or fork. Thanks.
![image](https://user-images.githubusercontent.com/17072625/111990517-b5f9eb80-8ae9-11eb-8641-2d98a6144d1b.png)

**Comment by chenzhang2006** [comment]
This demo is intended for publishing and consuming packages. Whether the artifactory(GH packages in this case) is private or public is up to how you or your company configures it to. E.g. if the library is published to a private _GH packages_ repository that belongs to your company, then all the published packages are only visible within the enterprise network. Does that make sense?
